project:
  type: book

book:
  title: "COVID-19 Infections"
  author:
  - "Rex W. Douglass"
  - "Thomas L. Scherer"
  - "Erik A. Gartzke"
  date: "8/7/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: cpas_covid_19.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

